sudo: required
services:
  - docker


before_install: 
   - docker build -t  mhassan654/react-with-docker -f Dockerfile.dev .


script: 
  - docker run mhassan654/react-with-docker npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "React Docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-699108825240"
  bucket_path: "React Docker"
  on: 
    branch: main
    